expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: 35.192.45.39.nip.io
    exposer: Ingress
    http: "true"
    tlsacme: "false"
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

global:
  keycloak:
    url: "http://jx-staging-quickstart-http.jx-staging.35.192.45.39.nip.io/auth"

activiti-cloud-query:
  service:
    annotations:
      fabric8.io/expose: "false"
      
activiti-cloud-gateway:
  service:
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.path: /
      fabric8.io/ingress.name: activiti
      fabric8.io/ingress.annotations: |-
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/cors-allow-headers: *
        nginx.ingress.kubernetes.io/enable-cors: true
        nginx.ingress.kubernetes.io/x-forwarded-prefix: true
